name = "Factions Research 1.0"
uid = "d592aae4-56ae-418b-ace6-994f5e80a0b8"
version = 1.0
copyright = "Gurzil"
description = "Add Upgrade to ACU allowing them build T1 land factory of a specific faction - By Gurzil"
author = "Gurzil"
icon = "/mods/FactionsResearch/factions.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}