name = "Factions Research"
uid = "7c0dce67-cff6-4343-807b-28b1b48bfda5"
version = 1
copyright = "Gurzil"
description = "Add Upgrade to ACU allowing them build T1 land factory of a specific faction - By Gurzil"
author = "Gurzil"
icon = "/mods/FactionsResearch/factions.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}